### ISSUE TITLE
name is now a required property

### ISSUE THREAD

**Issue by Odonno** [HarryChen0506/react-markdown-editor-lite#102]
I just upgraded this library to the latest version and now I got one error which is that `name` is now a required property of the `MdEditor` component.

I would like to know why the changes? Why is it required? And most importantly how does it affect my app?

Thank you, and thank you for this library.

**Comment by sylingd** [comment]
Where did you see this error? I tried it just now, `name` is not required

![image](https://user-images.githubusercontent.com/5326684/77756467-2fdbce00-706a-11ea-8f9f-507f4ddbffb8.png)

**Comment by Odonno** [comment]
I am using the version 0.4.8 with TypeScript. The type definition has some required properties:

* name
* value
* renderHTML

I need to use `value` and `renderHTML` but if I do not set a name, the `tsc` compiler is not happy. :(

**Comment by sylingd** [comment]
0.4.8 is no longer maintain, try to upgrade to 1.0.2
