### ISSUE TITLE
Navigator not available when using SSR 

### ISSUE THREAD

**Issue by kimgysen** [HarryChen0506/react-markdown-editor-lite#103]
My application renders react components in both server and client (SSR), and I'm transpiling my server as well as client code with Webpack.  
I run into some problems compiling this package at the server because navigator is not available in NodeJS environment.  

Is it possible to add an extra check on existence of the navigator variable, in order to avoid this compilation problem? 
Thanks.

**Comment by sylingd** [comment]
Please using client-side render, for example, in next.js, you can use:
```js
import dynamic from 'next/dynamic'
import 'react-markdown-editor-lite/lib/index.css';

const MdEditor = dynamic(() => import('react-markdown-editor-lite'), {
  ssr: false
});

export default function() {
  return (      
    <div style="height: 500px">
      <MdEditor
        value=""
        renderHTML={/* Render function */}
      />                
    </div>
  )
}
```

**Comment by kimgysen** [comment]
I'm not using next.js. The issue is related to Babel compile the server scripts, whereas the React modules that I use are 'universal' components. 

I resolved the problem by adding a shim to my webpack config. 
Probably this is indeed not something that should be resolved in the library as it is only used client side.
