### ISSUE TITLE
How to use getHtmlValue in react hooks

### ISSUE THREAD

**Issue by kannanseeni** [HarryChen0506/react-markdown-editor-lite#104]
```
const handleGetHtmlValue = () => {    
    alert(MdEditor.getHtmlValue())
  }
```
`<MdEditor 
            **_ref={node => this.mdEditor = node}_**
            value={MOCK_DATA}
            style={{height: `'400px'}}`
            renderHTML={this.renderHTML}
            config={{
              view: {
                menu: true,
                md: true,
                html: true,
                fullScreen: true
              },
              imageUrl: 'https://octodex.github.com/images/minion.png'
            }}
            onChange={this.handleEditorChange} 
            onImageUpload={this.handleImageUpload}
            // onCustomImageUpload={this.onCustomImageUpload} // if using onCustomImageUpload, onImageUpload will be not working
            onBeforeClear={this.onBeforeClear}
          />`
showing error

**Comment by sylingd** [comment]
Use `useRef` to get editor's instance and call it

```js
import * as React from 'react';

function MyEditor() {
  const editor = React.useRef(null);
  const someCallback = () => {
    if (editor.current) {
      console.log(editor.current.getHtmlValue());
    }
  };
  return (
    <Editor ref={editor} renderHTML={/* ... */} />
  );
}
```

**Comment by johnpaul89** [comment]
Hey @kannanseeni Did you manage to use it in hooks? 
If you did how did you getHtmlValue?
