### ISSUE TITLE
Can we use Keyboard shortcuts ?

### ISSUE THREAD

**Issue by singhiam** [HarryChen0506/react-markdown-editor-lite#105]
Hi Support,

Can we use Keyboard shortcuts using this module ?  

Thanks

**Comment by sylingd** [comment]
Of course-, write a plugin, using `on('keydown', e => console.log(e))` or `onKeyboard` to listen keyboard events, and do other things you like

**Comment by singhiam** [comment]
Thanks For Your Response @sylingd . this feature is already there or I need to do something extra for this. like to create own plugin .
