### ISSUE TITLE
How to auto size the editor pane

### ISSUE THREAD

**Issue by barbalex** [HarryChen0506/react-markdown-editor-lite#106]
Is it possible to have the editor pane grow to always show all it's content?

**Comment by sylingd** [comment]
I have implemented a auto-resize plugin and it will be available in the next version

**Comment by sylingd** [comment]
I have released 1.1.0, please upgrade and have a try.
Docs here: https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/docs/plugin.md

**Comment by barbalex** [comment]
```js
MdEditor.use(Plugins, {
  min: 100,
  max: 1000,
})
```
does not seem to influence anything in my case.

But it is possible that I have not implemented it correctly: https://github.com/barbalex/apf2/blob/edeac59d7ea2a6de27519809f999c586ac98c67c/src/components/shared/MarkdownFieldFormik/MarkdownFieldFormikGrowing.js#L10-L13

**Comment by sylingd** [comment]
Plugins -> Plugins.AutoResize
```js
MdEditor.use(Plugins.AutoResize, {
  min: 100,
  max: 1000,
})
```

**Comment by barbalex** [comment]
This [(see my code)](https://github.com/barbalex/apf2/blob/283f5acefae1d35274a847d7763d122fefd2d302/src/components/shared/MarkdownFieldFormik/MarkdownFieldFormikGrowing.js#L10-L13) results in the following `Invalid hook call` error where `index.js:1` seems to be in react-markdown-editor-lite:
<img width="537" alt="error_invalid_hook_call" src="https://user-images.githubusercontent.com/669783/80979949-4a9f2080-8e28-11ea-9917-bebdd67d1662.png">

**Comment by sylingd** [comment]
I'm sorry that I found a dependency resolution bug just now, it may be related to your situation. Try to upgrade to 1.1.1, does it resolved?

**Comment by barbalex** [comment]
Now it works like a charm. Thanks a lot!!!!

**Comment by barbalex** [comment]
With 
```
.editorpane {
  overflow-y: auto !important;
}
```

the scrollbar only shows when you reach the max height.
Seems nicer to me as now this rarely happens.

**Comment by sylingd** [comment]
> With
> 
> ```
> .editorpane {
>   overflow-y: auto !important;
> }
> ```
> 
> the scrollbar only shows when you reach the max height.
> Seems nicer to me as now this rarely happens.

The interface will shake on windows,  you can consider which one to use by yourself

**Comment by wezrule** [comment]
@sylingd was this intended to also work with just the html pane?
```
value = "Very long text ..."
config={{
     view: {
            menu: false,
            md: false,
            html: true,
     }
}
```
I want to display some markdown with a maximum height of just a html pane, is this possible? Could it be because this is undefined https://github.com/HarryChen0506/react-markdown-editor-lite/blob/33a94073d4f0d7de5256110dd727660f6f95644b/src/plugins/autoResize.tsx#L12 or just not called maybe?

**Comment by sylingd** [comment]
@wezrule Let me modify
