### ISSUE TITLE
Support ref on Editor

### ISSUE THREAD

**Issue by pdlug** [HarryChen0506/react-markdown-editor-lite#107]
I'm using [unform](https://unform.dev/) for form management and trying to create a custom input for MdEditor. This seems to require a `ref` to the underlying input/textarea but I don't see a way to pass this through to to the editor (example using simple code editor w/ unform shows what I'm trying to do: [unform react simple code editor example](https://unform.dev/examples/react-simple-code-editor) .

**Comment by sylingd** [comment]
See [this demo](https://codesandbox.io/s/modest-faraday-8h9nc)
