### ISSUE TITLE
useLocale: this.isAvaliable is not a function

### ISSUE THREAD

**Issue by hatsuo** [HarryChen0506/react-markdown-editor-lite#108]
https://github.com/HarryChen0506/react-markdown-editor-lite/blob/ddce8c0307049b32e641e2355ac805155ce58d52/src/editor/index.tsx#L68

You may want to replace this line by:
```js
static useLocale = i18n.setCurrent.bind(i18n);
```
This makes sure that the function is called in the right context.

**Comment by sylingd** [comment]
fixed
