### ISSUE TITLE
index.js does not match the corresponding name on disk

### ISSUE THREAD

**Issue by JCoelhoo** [HarryChen0506/react-markdown-editor-lite#113]
Using version 1.1.0 and get this error when trying run.

./node_modules/react-markdown-editor-lite/lib/index.js
Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/React/react'.

Using create-react-app with react@16.13.1

**Comment by sylingd** [comment]
Fixed, I will release a new version later
