### ISSUE TITLE
controled component cant delete content

### ISSUE THREAD

**Issue by nfwyst** [HarryChen0506/react-markdown-editor-lite#114]
when use controled component by set value,  there is always a `<p>&lt;</p>` tag in the editor content that can not be removed

**Comment by sylingd** [comment]
You can see a controlled editor demo at [src/demo/index.tsx](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/demo/index.tsx), it works well.
In this demo, I use react-markdown, but if you are using other markdown parser, the preview area may be a little different

**Comment by nfwyst** [comment]
> You can see a controlled editor demo at [src/demo/index.tsx](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/demo/index.tsx), it works well.
> In this demo, I use react-markdown, but if you are using other markdown parser, the preview area may be a little different

ok, thanks
