### ISSUE TITLE
Configuring Theme

### ISSUE THREAD

**Issue by johnpaul89** [HarryChen0506/react-markdown-editor-lite#115]
I'm using Material-UI on my project where I have configured a dark theme using Material UIs ThemeProvider.

When my theme is on darkmode this editor doesn't change to dark, it just remains white.

Is this editor configurable with themes or even override the css themes.

Thanks.

**Comment by sylingd** [comment]
You can override by yourself.
Those files may helpful:
* Basic, including editor's basic styles and default preview styles: [src/editor/index.less](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/editor/index.less)
* Navigation bar (which has many function buttions): [src/components/NavigationBar/index.less](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/components/NavigationBar/index.less)
* Dropdown list, used in headers and tables: [src/components/DropList/index.less](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/components/DropList/index.less)
* Header list: [src/plugins/header/HeaderList.less](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/plugins/header/HeaderList.less)
* Table: [src/plugins/table/table.less](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/plugins/table/table.less)

**Comment by johnpaul89** [comment]
Thanks, let me check them.
