### ISSUE TITLE
Remove display both editor and preview

### ISSUE THREAD

**Issue by JCoelhoo** [HarryChen0506/react-markdown-editor-lite#116]
I'm trying to hide the both preview and editor side-by-side view mode so I can have either full-view preview or full-view editor.  
I don't see this option in the canView

**Comment by sylingd** [comment]
`canView.md = false` and `view.md = false` You can hide editor area.
`canView.html = false` and `view.html = false` You can hide preview area.

**Comment by JCoelhoo** [comment]
I want to have both full screen editor and preview. I want to remove side-by-side

**Comment by sylingd** [comment]
You should implement a mode toggle plugin by yourself. You can modify it based on the [default mode toggle plugin](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/plugins/modeToggle.tsx)
