### ISSUE TITLE
怎么使用本地静态图片，谢谢

### ISSUE THREAD

**Issue by zhangshuai0101** [HarryChen0506/react-markdown-editor-lite#12]

**Comment by HarryChen0506** [comment]
可以利用new FileReader() ，将file转化成base64格式，然后用<img src="data:image/jpeg;base64,这里是数据省略..." />这样到方式显示图片即可。文档案例有写handleImageUpload这个函数，里面有案例，只不过那个案例多转化成了Blob格式。

**Comment by NewHubBoy** [comment]
![RUNOOB 图标](http://static.runoob.com/images/runoob-logo.png)
