### ISSUE TITLE
Fullscreen Styles / trigger

### ISSUE THREAD

**Issue by shomzie324** [HarryChen0506/react-markdown-editor-lite#121]
Is there a way to ensure the full screen editor follows the constraints I need for my app? I was thinking to have a trigger that updates my component's state. If I use the styles prop it will apply to both full screen and non full screen modes (e.g add top style so that I don't cover my app bar). I was wondering if either the full screen event trigger exists or if styles can be applied only to the full screen version somehow. Thanks !

**Comment by shomzie324** [comment]
I ended up resolving the issue for the time being by adjusting my components around the editor but ideally it would be nice to have more comprehensive control of the editor via props as opposed to building a plugin for it.

**Comment by sylingd** [comment]
You can write a plugin, listen `fullscreen` event, and set editor's styles

**Comment by shomzie324** [comment]
thanks !
