### ISSUE TITLE
React hook warning: componentWillReceiveProps has been renamed

### ISSUE THREAD

**Issue by puranis038** [HarryChen0506/react-markdown-editor-lite#123]
> react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: n

**Comment by puranis038** [comment]
It would be great if we get the updated version.

**Comment by sylingd** [comment]
Where did you see this warning? This editor does not using `componentWillReceiveProps`

**Comment by puranis038** [comment]
No. I am seeing this warning from the console or when testing the file. We are not using _componentWillReceiveProps_ in the component but we can see from the imported library of this editor (in node_modules). I am using the latest version of React which doesnt support the componentWillReceiveProps. So it asks to migrate to updated react unsafe component lifecycle.

**Comment by sylingd** [comment]
Can you give me a minimal reproduction? I have tested latest react in [CodeSandbox](https://codesandbox.io/s/rmel-in-react-experimental-req0u) and I didn't see any warnings.
Please make a minimal reproduction with codesandbox. If your bug involves a build setup, you can create a project using create-react-app and provide the link to a GitHub repository.

**Comment by puranis038** [comment]
Okay!

**Comment by puranis038** [comment]
I have a created a new project and pushed it. Here is the link: https://github.com/puranis038/ReactTextEditor. Once running the project, you can see it in console window.

**Comment by sylingd** [comment]
Please using latest version

**Comment by puranis038** [comment]
react-markdown-editor-lite": "^0.4.8 is the latest version that I am using it.

**Comment by sylingd** [comment]
latest version is 1.1.3

**Comment by puranis038** [comment]
I have upgraded to latest version now but the I am getting like the snapshot shown.
![MdEditor](https://user-images.githubusercontent.com/6563412/83540519-c0b2a800-a4f8-11ea-9e50-7a4295080b0a.PNG)

**Comment by sylingd** [comment]
import css by yourself. see demo in readme.md

**Comment by puranis038** [comment]
Yes. I found that and worked. Thanks!
