### ISSUE TITLE
HTML element image upload

### ISSUE THREAD

**Issue by tiotdev** [HarryChen0506/react-markdown-editor-lite#124]
I want to save the dimensions of the uploaded image that are already returned by my custom onImageUpload function. Instead of returning a markdown image code, I would like to insert a html <img /> element with alt, width, height and src attributes. Is there any way to do this?

**Comment by sylingd** [comment]
Follow those steps:
1. Remove default image plugin ([docs here](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/docs/plugin.md))
2. Write your custom upload plugin, using [insertPlaceholder or insertText API](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/docs/api.md#insertplaceholder-1) to add your html code
3. Make sure that your markdown parser allow you use html code, it depends on what parser you are using.

**Comment by tiotdev** [comment]
Thanks for your help! Is there any way to modify the drag'n drop image upload as well to return a html element instead?

**Comment by sylingd** [comment]
> Thanks for your help! Is there any way to modify the drag'n drop image upload as well to return a html element instead?

You can put editor in another element, listen drop event on it, and insert text with editor's API. such as:

```js
const editorRef = useRef(null);
const handleUpload = (e) => {
	// Prevent default events
	e.preventDefault();
	e.stopPropagation();
	// Upload, and get image's URL
	const url = 'xxx';
	// Get editor's ref, and call its API
	if (editorRef.current) {
		editorRef.current.insertText(`<img src="${url}" />`);
	}
}
```
```html
<div onDrop={handleUpload}>
	<Editor ref={editorRef} /* ... */ />
</div>
```
