### ISSUE TITLE
Gatsby/SSR: window is not defined when building

### ISSUE THREAD

**Issue by marcinczenko** [HarryChen0506/react-markdown-editor-lite#127]
Perhaps it would be nice to add instructions on how to integrate with Gatsby so that the users do not get `window is not defined` error when doing Gatsby Build. Gatsby is also doing SSR-kind of thing when building, which causes the error mentioned.

It would be nice if react-markdown-editor-lite does try to access `window` directly (or do so only after component mounts in an effect), but I currently use the following "quick fix" to get it work smoothly in development and build without an error.

> **UPDATE:** The presented code snippet below is one of the recommended ways as described on https://www.gatsbyjs.org/docs/using-client-side-only-packages/. Comparing to the original I have updated this code snippet only in that `<Suspense>...</Suspense>` part is now protected by a conditional so that it only renders on the client side.

```javascript
import React, { useEffect, useCallback, useRef, Suspense } from 'react'
// import style manually
import 'react-markdown-editor-lite/lib/index.css'

import MarkdownIt from 'markdown-it'
const MdEditor = React.lazy(() => import('react-markdown-editor-lite'))

const Home = () => {
  const mdParser = useRef(undefined)
  const isSSR = typeof window === 'undefined'
  useEffect(() => {
    mdParser.current = new MarkdownIt(/* Markdown-it options */)
  }, [])
  const handleEditorChange = useCallback(({ html, text }) => {
    console.log('handleEditorChange', html, text)
  }, [])

  return (
    <div>
      {!isSSR &&
        <Suspense fallback={<div />}>
          <MdEditor
            value=''
            style={{ height: '500px' }}
            renderHTML={(text) => mdParser.current.render(text)}
            onChange={handleEditorChange}
          />
      </Suspense>}
    </div>
  )
}
```

Or maybe you can recommend is a more generic/backward compatible way of getting it work nicely with Gatsby. I can get it work without suspense as well, but it feel dirtier and brakes HMR in development.

**Comment by marcinczenko** [comment]
Yes, I saw this example. I tried to find something that does not depend on `next/dynamic` and `Suspense` looks like client-side render (it does not even support SSR at the moment).

**Comment by sylingd** [comment]
I added more instructions in README.md
