### ISSUE TITLE
Editor's textarea id attribute should be configurable

### ISSUE THREAD

**Issue by vincent-vieira** [HarryChen0506/react-markdown-editor-lite#128]
Hello there,

Started using your component today and it's amazing, very practical. Thank you for your work 😄 

But it's breaking all my *testing-library* tests using *ByLabelText* query. The textarea should have the **id** attribute with the same value as the **for** attribute of the label. But the id attribute is not configurable, [hardcoded with the 'textarea' value](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/editor/index.tsx#L641).

In my opinion, it should be configurable. Is that possible ?
Thanks in advance

**Comment by sylingd** [comment]
Hello, I have released v1.1.5, this feature is already available

**Comment by vincent-vieira** [comment]
Great, thank you so much !
