### ISSUE TITLE
Blank Render with Multiple Instances

### ISSUE THREAD

**Issue by F1LT3R** [HarryChen0506/react-markdown-editor-lite#131]
Hi @HarryChen0506i - firstly, thanks for the awesome plugin. It's amazing.

I'm having trouble using multiple instances of the editor. Perhaps there's a simple solution?

### Details

When I have two editors on the page, and update the focused one, the unfocused editor goes blank.

![ScreenFlow](https://user-images.githubusercontent.com/1218446/84412036-a48bc680-abdc-11ea-9e3f-270dad95d9c2.gif)

Note:

1.  When I load the page, both editors show the correct content.
2. When I use one editor, other other goes blank.

### Code

```jsx
function MarkdownInput({ name, value, onChange }) {
  const classes = useStyles();

  return (
      <MdEditor
        id={name}
        value={value}
        style={{ height: '400px' }}
        renderHTML={(text) => mdParser.render(text)}
        onChange={onChange}
      />
  );
}


export default function Editors() {
  const [state, setState] = React.useState({
    editorOne: '### Test 1\n\n1. Markdown\n2. Supported',
    editorTwo: '### Test 2\n\n1. Markdown\n2. Supported',
  });

  return (
    <form noValidate autoComplete="off">
      <MarkdownInput
        name="editorOne"
        value={state.editorOne}
        onChange={({ text }) => {
          setState({ editorOne: text });
        }}
      />

      <MarkdownInput
        name="build"
        value={state.editorTwo}
        onChange={({ text }) => {
          setState({ editorTwo: text });
        }}
      />
    </form>
  )
};
```

**Comment by vincent-vieira** [comment]
If I'm not mistaken, the setter returned by _useState_ wipes the previous state and replaces it by the supplied new state. **It's not the same behavior** as the setState method available on React class components.

So the library's not the problem, your code is. Just change both **setState**s like that and it should work, state will be updated for a property without overwriting the other one :

`setState((previousState) => ({ ...previousState, editorOne: text }));`
`setState((previousState) => ({ ...previousState, editorTwo: text }));`

**Comment by sylingd** [comment]
Thanks @vincent-vieira , you should change your `setState` to:
```
setState((previousState) => ({ ...previousState, editorOne: text }));
// or
setState({ ...state, editorOne: text });
```

**Comment by F1LT3R** [comment]
Thanks guys!
