### ISSUE TITLE
I'd like to customize which options appears on 'fonts' plugin

### ISSUE THREAD

**Issue by durancristhian** [HarryChen0506/react-markdown-editor-lite#132]
Hi!, first of all, thank you so much for creating this project. It's not only the easy one I've ever tested but the most easy one to integrate and works like a charm 😀 

I think that a way to choose **which** buttons to render on the `fonts` plugin **and** the possibility to toggle an action on the editor without changing current behavior would be awesome to easily customize the editor to match any design. 

I know that the API allows me to do it by my own but I'd need to rewrite all the components and I'd loose future improvements in this sense.

Is that possible somehow or in the roadmap?

**Comment by durancristhian** [comment]
I didn't look to the code too much but I think that, with some guidance, I could probably implement something regarding this if you think it's worthy. Just let me know.

**Comment by sylingd** [comment]
https://github.com/HarryChen0506/react-markdown-editor-lite/commit/8fd8d77ac44c1f1dfac804f144f1384d4f020006

**Comment by durancristhian** [comment]
Awesome! I'll be pending on the release to start using it :)

Feel free to close this issue if you want
