### ISSUE TITLE
Markdown editor hangs on image upload

### ISSUE THREAD

**Issue by Reine0017** [HarryChen0506/react-markdown-editor-lite#135]
When i click the image upload icon and then use the handleImageUpload function, my whole react app freezes.

**Comment by sylingd** [comment]
Please make a minimal reproduction with codesandbox.
If your bug involves a build setup, you can create a project using create-react-app and provide the link to a GitHub repository.

**Comment by Reine0017** [comment]
Thank you for your comment I'll do that! :)

**Comment by Reine0017** [comment]
`import React, { useState } from "react";
import MarkdownIt from "markdown-it";
import MdEditor, { Plugins } from "react-markdown-editor-lite";
// import style manually
import "react-markdown-editor-lite/lib/index.css";
import axios from "axios";
import MarkdownItIns from "markdown-it-ins";

// Initialize a markdown parser
const mdParser = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
}).use(MarkdownItIns);

function CreateProjectTemplate() {
  //MdEditor.use(Plugins);
  const plugins = [
    "fonts",
    "my-plugins",
    "link",
    "clear",
    "image",
    "logger",
    "mode-toggle",
    "full-screen",
  ];
  const [value, setValue] = useState({ text: "", html: "" });

  const handleEditorChange = (content, event) => {
    setValue((newValue) => {
      newValue.text = content.text;
      newValue.html = content.html;
      return {
        ...newValue,
      };
    });
  };

  const handleImageUpload = (file) => {
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = (data) => {
        resolve(data.target.result);
      };
      reader.readAsDataURL(file);
    }).then(console.log("done"));
  };

  return (
    <>
      <MdEditor
        plugins={plugins}
        value="
      Try to use ![image](INSERT YOUR IMAGE_URL_HERE) to insert image"
        style={{ height: "500px" }}
        renderHTML={(text) => mdParser.render(text)}
        onChange={handleEditorChange}
        onImageUpload={handleImageUpload}
      />
    </>
  );
}

export default CreateProjectTemplate;
`

**Comment by Reine0017** [comment]
```
import React, { useState } from "react";
import MarkdownIt from "markdown-it";
import MdEditor, { Plugins } from "react-markdown-editor-lite";
// import style manually
import "react-markdown-editor-lite/lib/index.css";
import axios from "axios";
import MarkdownItIns from "markdown-it-ins";

// Initialize a markdown parser
const mdParser = new MarkdownIt({
  html: true,
  linkify: true,
  typographer: true,
}).use(MarkdownItIns);

function CreateProjectTemplate() {
  //MdEditor.use(Plugins);
  const plugins = [
    "fonts",
    "my-plugins",
    "link",
    "clear",
    "image",
    "logger",
    "mode-toggle",
    "full-screen",
  ];
  const [value, setValue] = useState({ text: "", html: "" });

  const handleEditorChange = (content, event) => {
    setValue((newValue) => {
      newValue.text = content.text;
      newValue.html = content.html;
      return {
        ...newValue,
      };
    });
    console.log("handleEditorChange", content, event);
    console.log(value);
  };

  const handleProjectTemplateSubmit = () => {
    console.log(value, "submitted");
    axios
      .post("/api/createprojtemplate", {
        projTemp: value,
      })
      .then((response) => {
        console.log(response.data);
      });
  };

  const handleImageUpload = (file) => {
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = (data) => {
        resolve(data.target.result);
      };
      reader.readAsDataURL(file);
    }).then(console.log("done"));
  };

  return (
    <>
      <MdEditor
        plugins={plugins}
        value="
      Try to use ![image](INSERT YOUR IMAGE_URL_HERE) to insert image"
        style={{ height: "500px" }}
        renderHTML={(text) => mdParser.render(text)}
        onChange={handleEditorChange}
        onImageUpload={handleImageUpload}
      />
      <button onClick={handleProjectTemplateSubmit}>Submit</button>
    </>
  );
}

export default CreateProjectTemplate;
```

**Comment by Reine0017** [comment]
If I'm not wrong, I believe the problem is caused by the fact that image upload is done with base64 which means the whole image is encoded as a very long string - so this causes the markdown editor to output and show a reaaally long string which can potentially cause the freeze.

**Comment by sylingd** [comment]
> Is it possible to save document non-relative files or pasted images to a local relative folder instead of embedding images directly into the Markdown/HTML document as base64 embedded image content?

Just implement handleImageUpload by yourself
