### ISSUE TITLE
The underline font button might be broken

### ISSUE THREAD

**Issue by Reine0017** [HarryChen0506/react-markdown-editor-lite#136]

**Comment by HarryChen0506** [comment]
May be you need [markdown-it-ins](https://www.npmjs.com/package/markdown-it-ins),  a  plugin of  'mark-it'.

**Comment by Reine0017** [comment]
Thank you so much for getting back to me (really appreciate it). I'll check it out! :)

**Comment by Reine0017** [comment]
It got fixed! Thank you!! :)
