### ISSUE TITLE
HELP: 内置插件可以用自定义图标吗

### ISSUE THREAD

**Issue by yaohuangguan** [HarryChen0506/react-markdown-editor-lite#137]
有没有办法能更换内置插件的图标呢？

**Comment by HarryChen0506** [comment]
内置插件的图标是iconfont，你先尝试用css覆盖的方式去做替换。如果不行的话，我们再考虑从代码上去做扩展，支持用户自定义样式的前缀，或者其他的方案去解决这个问题。欢迎随时反馈

**Comment by yaohuangguan** [comment]
> 内置插件的图标是iconfont，你先尝试用css覆盖的方式去做替换。如果不行的话，我们再考虑从代码上去做扩展，支持用户自定义样式的前缀，或者其他的方案去解决这个问题。欢迎随时反馈

好的 我试试

**Comment by yaohuangguan** [comment]
貌似还是不太行通过css的方式 感觉不是很灵活，如果有办法可以把内置插件暴露出来，覆盖原有图标，但是依然保留插件功能就好了

**Comment by sylingd** [comment]
可以使用CSS方式替换，例如这个例子替换了标题的图标：
https://codesandbox.io/s/rmel-demo-replace-icon-pl1n3?file=/src/App.js

**Comment by HarryChen0506** [comment]
@sylingd 我感觉在预置内置插件这一步上，还可以弄个钩子给用户，比如‘installDefaultPlugins’这样的。在这个钩子里面注册插件。当用户不使用这个api,我们就用自己默认的。这样用户就可以更换内置组件了。
![image](https://user-images.githubusercontent.com/21263805/86212405-8e08d780-bbaa-11ea-9be7-54a448412111.png)

**Comment by yaohuangguan** [comment]
![image](https://user-images.githubusercontent.com/43796777/86215298-02457a00-bbaf-11ea-9fe6-1f8f3d94cd49.png)
我用的svg，有啥办法能把font-family不设置的时候这个框去掉嘛。 另外怎么修改多个？我用.rmel-icon-font-size:nth-of-type(2):before  这种，不太行啊

**Comment by yaohuangguan** [comment]
> @sylingd 我感觉在预置内置插件这一步上，还可以弄个钩子给用户，比如‘installDefaultPlugins’这样的。在这个钩子里面注册插件。当用户不使用这个api,我们就用自己默认的。这样用户就可以更换内置组件了。
> ![image](https://user-images.githubusercontent.com/21263805/86212405-8e08d780-bbaa-11ea-9be7-54a448412111.png)

我感觉可以弄个钩子像getCustomIcon什么的，如果用户提供了图标，就渲染用户的否则就用默认的。功能还是能保留,我觉得主要是像换icon的情况比较多吧，完全替换内置组件没必要，否则就自定义就好了

**Comment by yaohuangguan** [comment]
顺便问下，editor.insertMarkdown('link', {
            linkUrl: 'hahahahahhah'
        });， 这个貌似没有效果？linkUrl显示不出

**Comment by HarryChen0506** [comment]
> > @sylingd 我感觉在预置内置插件这一步上，还可以弄个钩子给用户，比如‘installDefaultPlugins’这样的。在这个钩子里面注册插件。当用户不使用这个api,我们就用自己默认的。这样用户就可以更换内置组件了。
> > ![image](https://user-images.githubusercontent.com/21263805/86212405-8e08d780-bbaa-11ea-9be7-54a448412111.png)
> 
> 我感觉可以弄个钩子像getCustomIcon什么的，如果用户提供了图标，就渲染用户的否则就用默认的。功能还是能保留,我觉得主要是像换icon的情况比较多吧，完全替换内置组件没必要，否则就自定义就好了

这个细粒度太小，不合理。

**Comment by sylingd** [comment]
> 有啥办法能把font-family不设置的时候这个框去掉嘛

用CSS隐藏掉
```css
.rmel-icon-bold:before {
  display: none;
}
```

> 另外怎么修改多个

每个按钮都有唯一的class名称，F12看一下

**Comment by sylingd** [comment]
https://codesandbox.io/s/rmel-demo-replace-icon-pl1n3
