### ISSUE TITLE
ISSUE:滚动同步的时候，左边滑到底，md解析并不会到底

### ISSUE THREAD

**Issue by yaohuangguan** [HarryChen0506/react-markdown-editor-lite#138]
我在实际使用时候发现了这个问题，demo貌似也是的，https://harrychen0506.github.io/react-markdown-editor-lite/  

有什么办法能解决一下吗？

**Comment by HarryChen0506** [comment]
这块是个体验上的小问题，我们也没处理好，你要是感兴趣，可以帮助一起解决下

**Comment by sylingd** [comment]
已解决

**Comment by HarryChen0506** [comment]
> 已解决

新版本解决啦？

**Comment by yaohuangguan** [comment]
> 这块是个体验上的小问题，我们也没处理好，你要是感兴趣，可以帮助一起解决下

好啊，可以一起看 怎么把这个编辑器做得更好

**Comment by yaohuangguan** [comment]
> 已解决

要发新版吗？

**Comment by HarryChen0506** [comment]
> 已解决

太酷了

**Comment by sylingd** [comment]
> > 已解决
> 
> 要发新版吗？

是的

**Comment by yaohuangguan** [comment]
> > > 已解决
> > 
> > 
> > 要发新版吗？
> 
> 是的

期待

**Comment by yaohuangguan** [comment]
> > > 已解决
> > 
> > 
> > 要发新版吗？
> 
> 是的

麻烦问下，大概什么时候会发新版呢？

**Comment by sylingd** [comment]
周末吧
