### ISSUE TITLE
Editor.use is not a function

### ISSUE THREAD

**Issue by daveteu** [HarryChen0506/react-markdown-editor-lite#139]
不知道哪里做错了。放NewApp里面或外面都不行。

Editor是能用的，只是不能用Plugin。

我用的是NextJS
```
const Editor = dynamic(() => import('react-markdown-editor-lite'), {
    ssr: false
  });

const { PluginProps } = dynamic(() => import('react-markdown-editor-lite'), {
    ssr: false
 });

const MDDivider = (PluginProps) => {

    const addDivider = () => {
        props.editor.inserText('[[-]]');
    }

    return (
        <span onClick={addDivider} className="button" title="Divider"><HorizontalSplitIcon /></span>
    )
}

MDDivider.align = 'right';
MDDivider.pluginName = 'divider';

//NewApp Component
export default  (props) => {
Editor.use(MDDivider)
.....

<Editor 
....
/>
}
```

![image](https://user-images.githubusercontent.com/18649392/86318521-b9e89380-bc64-11ea-895a-ab227313dbf8.png)

**Comment by sylingd** [comment]
参考此处：https://github.com/GKD-OW/www-frontend/blob/master/src/components/editor/index.tsx

**Comment by daveteu** [comment]
行了！ 非常感谢！

**Comment by Gabsii** [comment]
I am facing the same problem currently. The link you provided doesn't seem to work - could you post an example? I would be willing to update the docs.

**Comment by sylingd** [comment]
> I am facing the same problem currently. The link you provided doesn't seem to work - could you post an example? I would be willing to update the docs.

https://codesandbox.io/s/next-js-80bne
