### ISSUE TITLE
这里如何使语法高亮呢

### ISSUE THREAD

**Issue by kurisLei** [HarryChen0506/react-markdown-editor-lite#14]
这里如何使语法高亮呢

**Comment by HarryChen0506** [comment]
可以使用highlight.js来做语法高亮。由于添加高亮功能会使得这个项目库的体积变得很大，违背了项目的轻量化的初衷，所以我关掉了高亮功能。你可以fork我的项目，把注释掉的代码打开即可。

**Comment by kurisLei** [comment]
> 可以使用highlight.js来做语法高亮。由于添加高亮功能会使得这个项目库的体积变得很大，违背了项目的轻量化的初衷，所以我关掉了高亮功能。你可以fork我的项目，把注释掉的代码打开即可。

谢谢，看到你注释的代码了。

**Comment by HarryChen0506** [comment]
0.4.0可以支持代码高亮了，不过需要自行配置
