### ISSUE TITLE
[HELP] renderHTML 返回promise 会有 编辑器快速输入而覆盖原有的使光标跑到最后

### ISSUE THREAD

**Issue by yaohuangguan** [HarryChen0506/react-markdown-editor-lite#145]
renderHTML={text => onRenderSource(text)}, onRenderSource 会去拿text查db的远程md, 里面await结果值, 然后return react-markdown组件

这么做貌似当编辑器输入很快时候并且在一段话中间打字时， 光标会自动移到最后 就是打字到最后去了

请问，这个问题怎么解决？

**Comment by sylingd** [comment]
已经排查出原因，稍后解决

**Comment by yaohuangguan** [comment]
> 已经排查出原因，稍后解决

大概啥时候发新版呢？

**Comment by yaohuangguan** [comment]
新版会解决这个问题是吗

**Comment by sylingd** [comment]
新版会解决。预计下周内发布

**Comment by yaohuangguan** [comment]
好的👍
