### ISSUE TITLE
Map shortcut keys to markdown editor ?

### ISSUE THREAD

**Issue by ad1992** [HarryChen0506/react-markdown-editor-lite#147]
Currently shortcut keys like `cmd+b/ctrl+b` don't work.  It would be great if the shortcut keys are supported.

**Comment by sylingd** [comment]
Implemented in v1.2.2.
To disable it, useing `config.shortcuts`

**Comment by ad1992** [comment]
Thank you @sylingd . Will upgrade 👍

**Comment by ad1992** [comment]
@sylingd ctrl+b works but in mac cmd keys are used so would be great if keys are mapped depending on platform
