### ISSUE TITLE
最先显示编辑器怎么配置

### ISSUE THREAD

**Issue by Lcj-space** [HarryChen0506/react-markdown-editor-lite#148]
## OS and browser
For example, Windows 10, Chrome 80.0.

## Description
For example, click a button, input some text, and something went wrong.

## Reproduction URL
Please make a minimal reproduction with [codesandbox](https://codesandbox.io/).
If your bug involves a build setup, please create a project using [create-react-app](https://github.com/facebook/create-react-app) and provide the link to a GitHub repository.

**Comment by Lcj-space** [comment]
![image](https://user-images.githubusercontent.com/22415092/88519598-f2417e80-d024-11ea-8242-ef47e202a2a9.png)
头部按钮不想隐藏

**Comment by sylingd** [comment]
view就是默认
头部隐藏是你自己用menu: false设置的

**Comment by Lcj-space** [comment]
好的，谢谢。
还有一个问题
![image](https://user-images.githubusercontent.com/22415092/89497812-aabead80-d7ef-11ea-93d8-34b2be154236.png)
红圈中的tool-bar 怎么去除牙

**Comment by sylingd** [comment]
config.canView.hideMenu = false

**Comment by guopei** [comment]
我刚开始也犯了这个错误，以为在view里面设置，后来仔细看才知道要在canView里面。view和canView的功能是不是有点重叠了？对初学者可能不太友好？

**Comment by sylingd** [comment]
> 我刚开始也犯了这个错误，以为在view里面设置，后来仔细看才知道要在canView里面。view和canView的功能是不是有点重叠了？对初学者可能不太友好？

不重叠，view是初始状态，可以被用户行为改变。canView是持久的状态，不可以被用户行为改变。

**Comment by guopei** [comment]
不好意思没太明白，如果canView里面设置了menu为false，hideMenu为true，那么hideMenu是不是还是可以把menu召唤出来？还是说因为canView里面的设置了false，所以无论如何不会被显示了？

**Comment by sylingd** [comment]
> 不好意思没太明白，如果canView里面设置了menu为false，hideMenu为true，那么hideMenu是不是还是可以把menu召唤出来？还是说因为canView里面的设置了false，所以无论如何不会被显示了？

如果你设置了canView.menu=false，那么hideMenu也会被自动设置成true。（目前的版本这一块逻辑还有点问题，但设计上是这这样的）
另外，canView的不可变，只是适用于内置插件的。其他插件通过API仍然可以更改这个状态。
