### ISSUE TITLE
[BUG]Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

### ISSUE THREAD

**Issue by bitores** [HarryChen0506/react-markdown-editor-lite#149]
## OS and browser
For example, Windows 10, Chrome 80.0.

## Description
For example, click a button, input some text, and something went wrong.

## Reproduction URL
Please make a minimal reproduction with [codesandbox](https://codesandbox.io/).
If your bug involves a build setup, please create a project using [create-react-app](https://github.com/facebook/create-react-app) and provide the link to a GitHub repository.
![image](https://user-images.githubusercontent.com/17512181/88764829-3446fd80-d1a8-11ea-8ea9-0e96fb17bb8f.png)
**Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.**

**Comment by sylingd** [comment]
Please make a minimal reproduction with codesandbox.

**Comment by bitores** [comment]
e.... in the file "src/editor/index.tsx", componentDidUpdate => componentWillReceiveProps, resolved the "Maximum update depth exceeded" bug
