### ISSUE TITLE
代码块颜色区分

### ISSUE THREAD

**Issue by aminwangaa** [HarryChen0506/react-markdown-editor-lite#152]
需要什么设置能让代码块内的代码显示颜色
```
const a = () => {
  console.log(2)
}
```

**Comment by HarryChen0506** [comment]
是指左边的输入框，还是右边的HTML里的代码显示颜色？

**Comment by aminwangaa** [comment]
像csdn的是两边都显示颜色
![image](https://user-images.githubusercontent.com/42959482/89367973-fa787880-d70c-11ea-84fc-5bb932de01b4.png)

**Comment by HarryChen0506** [comment]
左边的不支持颜色高亮，右边的可以，看案例
