### ISSUE TITLE
Guidance on how to set up the development environment?

### ISSUE THREAD

**Issue by guopei** [HarryChen0506/react-markdown-editor-lite#154]
First of all, thank you for your excellent work on this beautiful and powerful react markdown editor. 

I'd like to add some features (add katex support, modify some icons, remove split screen, etc.) to this editor and it would be nice to be able to access and modify the source code. I downloaded the code and embed it into my own react project. During compiling several error occurs like "Module not found", and "Attempted import error". I know it should be something really easy to solve, but I am a beginner without too much knowledge. 

It would be nice to have some instructions from you on how to set up the local development environment. 

Thank you!

**Comment by sylingd** [comment]
I noticed that you are **embed it into your own react project**, so I guess you are not install the editor's dependencies.

At least, those dependencies must be installed:
```
    "@types/node": "^13.5.1",
    "@types/react": "^16.8.22",
    "@types/react-dom": "^16.8.4",
    "@types/uuid": "^3.4.6",
    "eventemitter3": "^4.0.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "ts-node": "^8.6.2",
    "typescript": "^3.5.2",
    "uuid": "^3.4.0"
```

By the way, if you only want to add or remove some buttons into menu bar, write plugins may be a better choice. In face, the things you want do:
* katex support
  * just preview: depends on which markdown render you are using, for example, [markdown-it-katex](https://www.npmjs.com/package/markdown-it-katex)
  * add some buttons to help users write katex: wirte plugins, and call APIs like `insertText`, `setText`
* modify some icons: you can use CSS to modify built-in plugins icon, example: [rmel-demo-replace-icon](https://codesandbox.io/s/rmel-demo-replace-icon-pl1n3?file=/src/App.js)
* remove split screen
  * If you still require toggle edit and preivew mode, you shold rewrite built-in plugin `ModeToggle`
  * If you only want to keep one, just disable them with `config.canView`

**Comment by guopei** [comment]
Thank you!

Actually, I did the installment by `npm install <package name>` and then drag the package folder into my react folder. I modify the import part of my code to direct it to the local package. The first issue I got is "Attempted import error: 'PluginProps' is not exported from './plugins/Plugin'.", which is obviously there. I am looking at the typescript [official guide of Module Resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html)
for some clues. 

Let's say I want to write a plugin that only toggles between edit and preview, and not the split screen, or a plugin to insert the wrapper signs for latex like "$$", how do I test it? I think that requires I have a local environment, isn't it?

**Comment by guopei** [comment]
Well, I saw this nice [demo](https://codesandbox.io/s/rmel-demo-write-plugin-p82fc)  on how to write a plugin. It seems I need not a local environment. Looks like you have done a great job separating the plugins and the core framework!

My bad not reading things carefully! Thanks! (You can close this issue now if you want!)
