### ISSUE TITLE
Calling non static APIs?

### ISSUE THREAD

**Issue by guopei** [HarryChen0506/react-markdown-editor-lite#156]
I'd like to call the `setView` API when a self-defined button is clicked. However, the `setView` is a non-static function and I got the error "getView is not a funciton" using `MdEditor.setView`, which is imported using `import MdEditor from 'react-markdown-editor-lite'`. 

It seems I need to use an instance of MdEditor instead of the class variable itself, but how can I instantiate one? 

I can use `MdEditor.use` without problem because `use` is a static (class) property.

**Comment by sylingd** [comment]
Use ref, like `getMdValue` in this example: https://codesandbox.io/s/rmel-demo-ref-in-function-component-u04gb?file=/src/App.js

**Comment by Pats666** [comment]
I find that the `setView` API should use in this way:
```
import React, { useState } from 'react';
import MarkdownIt from 'markdown-it';
import MdEditor from 'react-markdown-editor-lite';
import 'react-markdown-editor-lite/lib/index.css';

const mdParser = new MarkdownIt(/* Markdown-it options */);

export default props => {
    const mdEditor = React.useRef(null);
    const clickclick = () => {
        mdEditor.current.setView({menu:false,html:true,md:false})
    }
    const click2 = () => {
        mdEditor.current.setView({menu:false,html:false,md:true})
    }
  return (
      <div>
        <MdEditor ref={mdEditor} style={{ height: '500px' }} renderHTML={text => mdParser.render(text)} view={{menu:false,html:true,md:false}} />
        <button onClick={clickclick}>111111</button>
        <button onClick={click2}>222222</button>
      </div>
    
  );
};
```
follow the document, i used to write like this:
`mdEditor.current.setView({to:{menu:false,html:true,md:false}})`
but it wont work.

**Comment by sylingd** [comment]
> I find that the `setView` API should use in this way:
> 
> ```
> import React, { useState } from 'react';
> import MarkdownIt from 'markdown-it';
> import MdEditor from 'react-markdown-editor-lite';
> import 'react-markdown-editor-lite/lib/index.css';
> 
> const mdParser = new MarkdownIt(/* Markdown-it options */);
> 
> export default props => {
>     const mdEditor = React.useRef(null);
>     const htmlMode = () => {
>         mdEditor.current.setView({menu:false,html:true,md:false})
>     }
>     const markdownMode = () => {
>         mdEditor.current.setView({menu:false,html:false,md:true})
>     }
>     const htmlAndMarkdownMode = () => {
>         mdEditor.current.setView({menu:false,html:true,md:true})
>     }
> 
>   return (
>       <div>
>         <MdEditor ref={mdEditor} style={{ height: '500px' }} renderHTML={text => mdParser.render(text)} view={{menu:false,html:true,md:false}} />
>         <button onClick={htmlMode}>htmlMode</button>
>         <button onClick={markdownMode}>markdownMode</button>
>         <button onClick={htmlAndMarkdownMode}>htmlAndMarkdownMode</button>
>       </div>
>     
>   );
> };
> ```
> 
> follow the document, i used to write like this:
> `mdEditor.current.setView({to:{menu:false,html:true,md:false}})`
> but it wont work.

Please submit a new issue with issue template
