### ISSUE TITLE
有序列表无序列表样式失效

### ISSUE THREAD

**Issue by Lcj-space** [HarryChen0506/react-markdown-editor-lite#160]
![image](https://user-images.githubusercontent.com/22415092/90712133-e9b32f80-e2d4-11ea-8b8f-84ec5ccac80f.png)

**Comment by Lcj-space** [comment]
这块是不是需要加什么特殊配置

**Comment by lishanshan023** [comment]
有序列表展示P元素，样式有误

**Comment by sylingd** [comment]
这取决于你所使用的markdown解析器。请前往相应的解析器进行反馈。
