### ISSUE TITLE
Customize plugins - Link with [](url) - want to add "url" text

### ISSUE THREAD

**Issue by harish-madugula** [HarryChen0506/react-markdown-editor-lite#162]
Hey there!
This package is one of the best among the available ones and works pretty nice.

I was wondering if we have any way to customize the **LINK PLUGIN** that we use.

What my requirement is when we click on **link** symbol, in the markup - **`[]()`** gets added.
Is there anyway that I can automatically add a text ( url in between the ( ) ) like this **`[](url)`** the way this github editor does when we click the above link symbol.

Or is there a way to customize the tooltip that occurs when we hover on the link symbol?

**`[](url)`** 

Thanks in advance.

**Comment by sylingd** [comment]
API Docs: https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/docs/api.md
Plugin demo: https://codesandbox.io/s/rmel-demo-write-plugin-p82fc
