### ISSUE TITLE
Demo for on / off?

### ISSUE THREAD

**Issue by guopei** [HarryChen0506/react-markdown-editor-lite#163]
Suppose I want to listen to the "fullscreen" state. When it changes, I'd like to make some changes to the surrounding divs of the editor. I know there's an API on/off for that, and I know how to use on/off from [your demo](https://codesandbox.io/s/rmel-demo-ref-in-function-component-u04gb?file=/src/App.js:382-392), but where should I register such an event listener? useref? usecallback? 

I am using function components all through my project...

**Comment by sylingd** [comment]
Plugin: https://codesandbox.io/s/rmel-demo-write-plugin-p82fc

Otherwise you should use ref
