### ISSUE TITLE
源文件和html同时显示为[object Object]是怎么回事

### ISSUE THREAD

**Issue by yangzy-dev** [HarryChen0506/react-markdown-editor-lite#166]
基于antd的react项目
...
import MarkdownIt from 'markdown-it'
import MdEditor from 'react-markdown-editor-lite'
import 'react-markdown-editor-lite/lib/index.css';

const handleEditorChange = (params:{html:string, text: string}) => {    
        console.log(params);// 打印为{html: "< p>[object Object]</ p>\n", text: "[object Object]"}，显示为什么会错误
}
...
return (
...
<MdEditor
                        style={{ height: "400px" }}
                        renderHTML={renderHtml}
                        onChange={handleEditorChange}
                    />
...
)

**Comment by sylingd** [comment]
Please make a minimal reproduction with [codesandbox](https://codesandbox.io/).

If your bug involves a build setup, please create a project using [create-react-app](https://github.com/facebook/create-react-app) and provide the link to a GitHub repository.

请使用[codesandbox](https://codesandbox.io/)建立一个最小复现。

如果您遇到的错误涉及构建设置，请使用[create-react-app](https://github.com/facebook/create-react-app)创建一个项目，并提供GitHub仓库链接。

**Comment by pyfs** [comment]
我也遇到了同样的问题；

**Comment by abigmiu** [comment]
```tsx
<Form.Item name="content" label="内容">
        <div> // 外面嵌套一层就可以了
              <MdEditor
                    style={{ border: '1px solid #ccc', height: '500px' }}
                    renderHTML={text => <ReactMarkdown children={text} />}
                    onImageUpload={onEditorUpload}
                 />
         </div>
 </Form.Item>
```
