### ISSUE TITLE
[BUG] Editor's background colour is black (cannot see text) and for some reason has horizontal display

### ISSUE THREAD

**Issue by Reine0017** [HarryChen0506/react-markdown-editor-lite#167]
## OS and browser
Ubuntu, Chrome Browser

## Description
The editor's background colour is now black for some reason. Thus, it is now impossible to see the text typed.
![Screenshot from 2020-11-25 23-54-56](https://user-images.githubusercontent.com/26247692/100244229-0a48f080-2f7a-11eb-98cc-1a3390cbe18a.png)

## Reproduction code

```
import React from "react";
import Editor from "react-markdown-editor-lite";
import ReactMarkdown from "react-markdown";
import "react-markdown-editor-lite/lib/index.css";

export default function App() {
  const mdEditor = React.useRef(null);

  return (
    <div className="App">
      <Editor
        ref={mdEditor}
        style={{
          height: "500px"
        }}
        renderHTML={(text) => <ReactMarkdown source={text} />}
      />
    </div>
  );
}
```

**Comment by Reine0017** [comment]
![Screenshot from 2020-11-26 00-41-50](https://user-images.githubusercontent.com/26247692/100249736-3f584180-2f80-11eb-9c43-2ef9985b2ecf.png)
I think the issue is caused by the import "react-markdown-editor-lite/lib/index.css";

.editor-container is somehow set to flex-direction: column; and background-color: hsl(225, 6%, 25%); by default. Anyway to override this?

**Comment by sylingd** [comment]
[lib/index.css](https://unpkg.com/react-markdown-editor-lite@1.2.2/lib/index.css) doesn't have any background styles about `.editor-container`. This style is written by yourself

**Comment by Reine0017** [comment]
Oh wait whut really oops..sorry let me double check >.<

**Comment by Reine0017** [comment]
Just wondering where the lib/index.css file is located?

**Comment by sylingd** [comment]
`lib/index.css` is a build product, only avaliable in a npm package. You can browse it at [unpkg](https://unpkg.com/react-markdown-editor-lite@1.2.2/lib/index.css), or install this package, and find it at `node_modules/react-markdown-editor-lite/lib/index.css`

**Comment by Reine0017** [comment]
Thank you so much for sending them! I'm still a little bit confused because I don't have any css files setting the .editor-container. I'll look into it though, thank you!
