### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by donnol** [HarryChen0506/react-markdown-editor-lite#169]
## OS and browser
ubuntu20.04 chrome

## Description
我把组件从0.4.2升级到1.2.2的时候，样式全乱了。

![格式乱了](https://user-images.githubusercontent.com/5707519/101316854-4a707300-3898-11eb-994a-2cf12410bbe8.png)

**Comment by sylingd** [comment]
需要自行引入样式，具体方式查看最新的使用说明

**Comment by donnol** [comment]
有链接嘛？我看了一遍README.md没找到。
