### ISSUE TITLE
序号渲染不正常

### ISSUE THREAD

**Issue by liaokaime** [HarryChen0506/react-markdown-editor-lite#170]
有序和无序序号的渲染不正常

![image](https://user-images.githubusercontent.com/27792976/101604424-de2e7480-3a3b-11eb-91a5-1d424eeef57c.png)

**Comment by sylingd** [comment]
预览区域的渲染效果取决于你自定义的markdown渲染器，与本编辑器无关。

**Comment by liaokaime** [comment]
谢谢，图上用的渲染器是markdown-it，我换成react-markdown后，有报错发生
```
  renderHTML(text: string) {
    // return this.mdParser.render(text);
    // Using react-markdown
    return React.createElement(ReactMarkdown, {
      source: text,
    });
  }
```
![image](https://user-images.githubusercontent.com/27792976/101606818-c4daf780-3a3e-11eb-8708-911b09da35a3.png)

**Comment by liaokaime** [comment]
我在react-markdown下找到了[这个问题](https://github.com/remarkjs/react-markdown/issues/518)，这可能是react-markdown的原因，降级react-markdown可能解决问题
