### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by serializedowen** [HarryChen0506/react-markdown-editor-lite#181]
## OS and browser
macOS 10.15    Chrome 86

## Description

输入一次会触发2次onChange

**Comment by sylingd** [comment]
Please make a minimal reproduction with codesandbox.
If your bug involves a build setup, please create a project using create-react-app and provide the link to a GitHub repository.
请使用codesandbox建立一个最小复现。
如果您遇到的错误涉及构建设置，请使用create-react-app创建一个项目，并提供GitHub仓库链接。
