### ISSUE TITLE
[BUG] Calling "onChange" twice

### ISSUE THREAD

**Issue by Nes-si** [HarryChen0506/react-markdown-editor-lite#183]
## Description
`onChange` function calling twice on every value changing. You can see it just in your [demo](https://codesandbox.io/s/rmel-demo-ref-in-function-component-u04gb), in the console.

## Reproduction URL
[demo](https://codesandbox.io/s/rmel-demo-ref-in-function-component-u04gb)

**Comment by vittoriozamboni** [comment]
It looks `onChange` is called twice here:

- https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/editor/index.tsx#L503
- https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/src/editor/index.tsx#L514

Shouldn't be called only the second time (after the HTML render)? Or having a props deciding (i.e. `onChangeStrategy: 'beforeHTMLRender' | 'afterHTMLRender' = 'afterHTMLRender`)?

**Comment by sylingd** [comment]
Added

**Comment by sylingd** [comment]
I have published 1.2.5-0, please check if the problem has been fixed
