### ISSUE TITLE
[BUG] Error notification when unmount fast during editing

### ISSUE THREAD

**Issue by a-tonchev** [HarryChen0506/react-markdown-editor-lite#186]
## OS and browser
Windows 10, Chrome

## Description
When making changes in the editor but unmount fast the editor component an error shows in the console.

## Reproduction URL

Open the link and start to remove text, while pressing backbutton. During text is still removing press fast "Hide Editor":

https://codesandbox.io/s/rmel-demo-ref-in-function-component-forked-i38eb?file=/src/App.js

Look at console:

![image](https://user-images.githubusercontent.com/54528540/104229217-a2306a00-5454-11eb-86c1-574a5a61d65e.png)

**Comment by sylingd** [comment]
Fixed

**Comment by sylingd** [comment]
I have published 1.2.5-0, please check if the problem has been fixed
