### ISSUE TITLE
code模块没有颜色高亮

### ISSUE THREAD

**Issue by leeyboy1992** [HarryChen0506/react-markdown-editor-lite#187]
编辑的code模块的时候没有颜色高亮是什么原因，是还要引入什么吗？

**Comment by sylingd** [comment]
本编辑器没有渲染功能。根据自己所使用的markdown渲染引擎，自行寻找相关插件

**Comment by tlylt** [comment]
Just in case someone has the same query~
If you are using highlightjs, you need to import the **CSS** into the page in order for the formatting to show up.

e.g. put this in your page
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css">`
