### ISSUE TITLE
正在使用，如何设置打开就是预览页面，不能编辑。

### ISSUE THREAD

**Issue by yiluxiangbei87110** [HarryChen0506/react-markdown-editor-lite#19]
正在使用，如何设置打开就是预览页面，不能编辑。

**Comment by sylingd** [comment]
如果希望用户不能编辑的话，为什么不直接渲染到页面上呢？

**Comment by HarryChen0506** [comment]
config={{
              view: {
                menu: false,
                md: false,
                html: true
              }
     }}, 这样就好了

**Comment by JaneSu** [comment]
![image](https://user-images.githubusercontent.com/20908447/62203467-d11c6280-b3bd-11e9-95eb-3a051420d3f8.png)

config的配置按照文档写了，但是依然会有那几个控制按钮，还是能打开markdown编辑，这个有配置能消除么

**Comment by HarryChen0506** [comment]
这个按钮不能通过配置消除。但是如果你只需要渲染的HTML,你可以使用组件HtmlRender```
import MdEditor from 'react-markdown-editor-lite'const HtmlRender =  MdEditor.HtmlRender// 使用：< HtmlRender /> 或者 <MdEditor.HtmlRender/>```源码里HtmlRender就是渲染的HTML.






------------------ 原始邮件 ------------------
发件人: "苏简"<notifications@github.com>; 
发送时间: 2019年7月31日(星期三) 晚上6:06
收件人: "HarryChen0506/react-markdown-editor-lite"<react-markdown-editor-lite@noreply.github.com>; 
抄送: "左边口袋"<402472857@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [HarryChen0506/react-markdown-editor-lite] 正在使用，如何设置打开就是预览页面，不能编辑。 (#19)





 
config的配置按照文档写了，但是依然会有那几个控制按钮，还是能打开markdown编辑，这个有配置能消除么

**Comment by HarryChen0506** [comment]
- 这个按钮不能通过配置消除。但是如果你只需要渲染的HTML,你可以使用组件HtmlRender
```
import MdEditor from 'react-markdown-editor-lite'
const HtmlRender =  MdEditor.HtmlRender
// 使用：< HtmlRender html={htmlStr} /> 或者 <MdEditor.HtmlRender html={htmlStr} />
```
- 源码里HtmlRender就是用来渲染的HTML的组件.

**Comment by Jansora** [comment]
这个问题可以通过css来解决
div..tool-bar {
    display:none;
}
F!2 debug看一下
