### ISSUE TITLE
[Issues encountered] Format lost when saved to mongodb

### ISSUE THREAD

**Issue by nyc001** [HarryChen0506/react-markdown-editor-lite#203]
This is a great Markdown editor, thanks. However, when I saved the text generated from this editor and saved to MongoDb, it lost its format when I retrieved them back. Any suggested ideas? I have googled this topic, and I haven't found much ways to solve this. thanks in advance

**Comment by sylingd** [comment]
Check whether the markdown text you get from `getText` API is the same as the one you get from mongodb later or not
