### ISSUE TITLE
[next.js addLocale support] maybe you can help

### ISSUE THREAD

**Issue by nyc001** [HarryChen0506/react-markdown-editor-lite#204]
I'm developing a project in next.js using your markdown editor. The following is my code:
const MdEditor = dynamic(() => import("react-markdown-editor-lite"), {
  ssr: false,
});

Per api doc, I am supposed to use Editor.addLocale('zh-TW', {
  btnHeader: '標頭',
  btnClear: '清除',
  btnBold: '粗體',
});
Editor.useLocale('zh-TW');

However, nextjs tells me that there is not useLocale function. Thanks

**Comment by sylingd** [comment]
see this demo: https://codesandbox.io/s/rmel-demo-with-next-js-80bne?file=/pages/locale.jsx

**Comment by nyc001** [comment]
It works like a charm. Thank you very much
