### ISSUE TITLE
关于有序列表和无序列表

### ISSUE THREAD

**Issue by liyaogang97** [HarryChen0506/react-markdown-editor-lite#206]
您好，我在使用您的这一款编辑器的时候有序列表和无须列表不自动扩展的问题，您那边有遇到过这种问题吗？

**Comment by djwlx** [comment]
有序和无序列表还有下划线，好像都不行

**Comment by liyaogang97** [comment]
> 有序和无序列表还有下划线，好像都不行

好像是的，请问您有什么好的markdown编辑器插件推荐呢？

**Comment by djwlx** [comment]
把markdown-it换成了markdown这个解析器也不行，好像是因为css渲染的原因,可以更换其他的试一试

**Comment by liyaogang97** [comment]
> 把markdown-it换成了markdown这个解析器也不行，好像是因为css渲染的原因,可以更换其他的试一试

我也找了好多插件，但是感觉都不是很好。

**Comment by sylingd** [comment]
目前没有实现自动扩展，已经计划

**Comment by sylingd** [comment]
目前beta版本有序列表和无需列表已经支持自动扩展，可更新至react-markdown-editor-lite@1.2.5-5测试

**Comment by liyaogang97** [comment]
感谢大佬
在2021年6月11日 ***@***.***> 写道：

***@***.***测试

**Comment by liyaogang97** [comment]
大佬，您的测试版本在哪里下载呢？npm下载可以吗？


| |
18338092415
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年6月11日 ***@***.***> 写道：


感谢大佬
在2021年6月11日 ***@***.***> 写道：

***@***.***测试

**Comment by sylingd** [comment]
就是npm啊，不然你还想在哪下……
（PS：最新的测试版是1.2.5-6）

**Comment by sylingd** [comment]
1.3.0已发布
