### ISSUE TITLE
[BUG] Underline should show as underline instead of +++

### ISSUE THREAD

**Issue by catherineluse** [HarryChen0506/react-markdown-editor-lite#210]
## OS and browser
For example, Windows 10, Chrome 80.0.

I used it in Chrome  91.0.4472.77 

## Description
I clicked the underline button. Instead of showing an underline, the text looked like "+++text+++" in both the markdown and HTML rendered version.

## Reproduction URL
It doesn't work in my local machine, but it also doesn't work in the official demo linked on the readme: https://codesandbox.io/s/rmel-demo-ref-in-function-component-u04gb

**Comment by HarryChen0506** [comment]
https://github.com/HarryChen0506/react-markdown-editor-lite/issues/99
https://github.com/HarryChen0506/react-markdown-editor-lite/issues/136
