### ISSUE TITLE
关于toolbar中表格不能使用的问题

### ISSUE THREAD

**Issue by liyaogang97** [HarryChen0506/react-markdown-editor-lite#215]
![image](https://user-images.githubusercontent.com/53807604/123533040-da96dc80-d744-11eb-802a-f6f53f13e0d2.png)

**Comment by qburst-mariya** [comment]
I also got the same issue, table options are not visible properly. Not working even in the given demo
![Screenshot from 2021-06-27 21-16-30](https://user-images.githubusercontent.com/75407195/123550879-21102980-d78d-11eb-97ab-3e85643962d3.png)

**Comment by sylingd** [comment]
fixed at 1.2.5-8
