### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by samit4me** [HarryChen0506/react-markdown-editor-lite#216]
This [change](https://github.com/HarryChen0506/react-markdown-editor-lite/commit/4d880648152ba290268530de080d1e8b2f7eda1d) was made back in Janurary but the latest published version 1.2.4 does not appear to have the change, so seeing dependency warnings with react 17.

`warning " > react-markdown-editor-lite@1.2.4" has incorrect peer dependency "react@^16.9.0".`

Sorry, didn't mean to report as bug, can't figure out how to remove it

**Comment by sylingd** [comment]
This change will be released at 1.2.5.

Now 1.2.5 is a beta version, I will release it soon

**Comment by samit4me** [comment]
Awesome, thanks for getting back so quickly 👍

**Comment by VenkatKaruna** [comment]
I have a plan to move my project to production. Its on pending due to reactJS version support issue.
Can you give me the release date of **ReactJS Version 17 Support**
So that I can plan accordingly.

**Comment by sylingd** [comment]
1.3.0 released
