### ISSUE TITLE
[想法] 老哥 上传图片转base64的话有没有办法在编辑器里不让base64那么长一传显示 占了编辑器好多地方

### ISSUE THREAD

**Issue by PDXing** [HarryChen0506/react-markdown-editor-lite#217]
## OS and browser
For example, Windows 10, Chrome 80.0.
例如：Windows 10，Chrome 80.0

## Description
For example, click a button, input some text, and something went wrong.
例如：点击某个按钮，输入某些文本，然后发现问题。

## Reproduction URL
Please make a minimal reproduction with [codesandbox](https://codesandbox.io/).
If your bug involves a build setup, please create a project using [create-react-app](https://github.com/facebook/create-react-app) and provide the link to a GitHub repository.
请使用[codesandbox](https://codesandbox.io/)建立一个最小复现。
如果您遇到的错误涉及构建设置，请使用[create-react-app](https://github.com/facebook/create-react-app)创建一个项目，并提供GitHub仓库链接。

**Comment by sylingd** [comment]
转base64只是demo里面的做法

实际建议你还是真正上传。不要搞存base64这种骚操作。。。。
