### ISSUE TITLE
How to avoid confirmation window popup on clicking delete icon?

### ISSUE THREAD

**Issue by qburst-mariya** [HarryChen0506/react-markdown-editor-lite#218]
![image](https://user-images.githubusercontent.com/75407195/123658703-97756000-d84f-11eb-9182-f5909b4ba754.png)

I would like to either have my custom confirmation on delete or I want to remove the confirmation. Is that possible

**Comment by HarryChen0506** [comment]
https://github.com/HarryChen0506/react-markdown-editor-lite/blob/master/docs/plugin.md

Maybe the custom plugin can help you solve the problem. Please read the doc above, and create your `clear plugin` extended from PluginComponent .

**Comment by qburst-mariya** [comment]
Ok Got it thanks
