### ISSUE TITLE
字体图标覆盖

### ISSUE THREAD

**Issue by JackAtlas** [HarryChen0506/react-markdown-editor-lite#22]
https://github.com/HarryChen0506/react-markdown-editor-lite/blob/9d44b108fda2a063c8a82c15c5647174abf399ec/src/components/Icon/font.less#L9

https://github.com/HarryChen0506/react-markdown-editor-lite/blob/9d44b108fda2a063c8a82c15c5647174abf399ec/src/components/Icon/font.less#L11

会把编辑器以外的字体图标给覆盖了。

**Comment by HarryChen0506** [comment]
刚才发布了新版本v0.4.2,应该能解决这个字体覆盖的bug,你试一下哈，有问题尽管提出来。

**Comment by JackAtlas** [comment]
😏 Nice~
