### ISSUE TITLE
[BUG] Underline not working in preview mode

### ISSUE THREAD

**Issue by VenkatKaruna** [HarryChen0506/react-markdown-editor-lite#220]
Underline not working in preview mode
![image](https://user-images.githubusercontent.com/317277/123841020-b0077800-d92c-11eb-8c98-a3633251536b.png)

**Comment by HarryChen0506** [comment]
https://github.com/HarryChen0506/react-markdown-editor-lite/issues/210

**Comment by VenkatKaruna** [comment]
OS: 
![image](https://user-images.githubusercontent.com/317277/123993118-cd4e4c00-d9e9-11eb-8f80-f7b3b5e8c8aa.png)

Browser: 
![image](https://user-images.githubusercontent.com/317277/123992985-b14aaa80-d9e9-11eb-97bb-684fa629d2e3.png)

**Comment by HarryChen0506** [comment]
https://github.com/HarryChen0506/react-markdown-editor-lite/issues/99
