### ISSUE TITLE
[FEAT]是否可以支持图片自定义展示方式

### ISSUE THREAD

**Issue by yoole5699** [HarryChen0506/react-markdown-editor-lite#223]
感谢大佬开源！

### 现状
看了下源码里当前渲染md的方式是直接把 [renderHTML](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/0ba874ed5e36503310dc1b4f7fc98b28a0e4c8b1/src/editor/index.tsx#L292) 的返回值html作为了 [HtmlRender](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/0ba874ed5e36503310dc1b4f7fc98b28a0e4c8b1/src/editor/index.tsx#L856) 的props，然后直接 [渲染](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/0ba874ed5e36503310dc1b4f7fc98b28a0e4c8b1/src/editor/preview.tsx#L41) 出来

### 疑问
可以提供API支持 配置图片(顺便支持下其它html tag就更好了) 用自定义的react组件 来进行渲染嘛，期待的API形如
`<Editor customHtmlRender={{ image: (imageProps) => React.ReactNode }} />`

**Comment by sylingd** [comment]
这个取决于你自己的HTML渲染引擎啊。你需要自定义的话就自定义渲染引擎，比如react-markdown可以替换掉默认的render。
