### ISSUE TITLE
[REQUEST] passing className props to MdEditor

### ISSUE THREAD

**Issue by daveteu** [HarryChen0506/react-markdown-editor-lite#236]
## Description
Can we request for `className` props to be passed to MdEditor (other than markdownClass and htmlClass)?

This allows developers to do CSS customization by targeting inner elements (e.g. using styled components).

E.g. htmlClass doesn't allow us to change the background colour of the preview panel, unless we override `section-container html-wrap` classes.

<img width="836" alt="image" src="https://user-images.githubusercontent.com/18649392/140805979-62c2bea2-97ff-4f0c-9006-538cf93bea98.png">

# 謝謝你！感恩！

**Comment by sylingd** [comment]
v1.3.2 has published
