### ISSUE TITLE
Can't get the markdown

### ISSUE THREAD

**Issue by lordkada** [HarryChen0506/react-markdown-editor-lite#24]
I'm trying to get the Markdown from the `handleEditorChange` as described in your first example but getting just undefined (whereas html is fine)...

```
handleEditorChange ({html, md}) {    
    console.log('handleEditorChange', html, md)
}
```

Any idea?

thanks in advance

**Comment by HarryChen0506** [comment]
sorry,  the part of  this doc about how to use "onChange" api was wrongly written. the key is 'text' ，not 'md'. so the correct writing is as follows. I will fix the problem as soon as possible.
```
  handleEditorChange = ({ html, text }) => {
     console.log('handleEditorChange', html，text)
  }
```

**Comment by lordkada** [comment]
Thx
