### ISSUE TITLE
1. 文本输入框内tab键被禁用了 ? 2: 如何高亮文本输入框

### ISSUE THREAD

**Issue by Jansora** [HarryChen0506/react-markdown-editor-lite#27]

**Comment by Jansora** [comment]
大佬能否帮忙解决下，如果没时间，提供下思路也可，谢谢。

**Comment by HarryChen0506** [comment]
1. 文本框的tab键无效？
解决：可以参考这篇文章https://www.jianshu.com/p/2732f6a2f398。因为textarea本身不支持tab键缩进，可以利用原生的api,对text内容做处理，加上两个或几个空格
2. 高亮文本输入框？
在对编辑器部分不更换textarea之前，无法使用高亮。你可以考虑不使用textarea作为文本编辑器，使用第三方的文本编辑器

**Comment by Jansora** [comment]
👌，谢谢
