### ISSUE TITLE
[Feature request] option to render React node instead of HTML

### ISSUE THREAD

**Issue by AustenLamacraft** [HarryChen0506/react-markdown-editor-lite#272]
I'd like to render the preview using [better-react-mathjax](https://github.com/fast-reflexes/better-react-mathjax), which uses a component `MathJax` (the nice thing about this approach is that it takes care of the styles). Thus it would be good to have the option of rendering a React node instead of HTML in `renderHTML`.

**Comment by AustenLamacraft** [comment]
Actually dd

**Comment by AustenLamacraft** [comment]
Turns out wrapping the whole editor component in `<MathJax>...</MathJax>` was all I needed (the editor text doesn't render)

**Comment by sylingd** [comment]
https://codesandbox.io/s/rmel-demo-ref-in-function-component-u04gb
