### ISSUE TITLE
Be able to add "name" prop to the textarea element

### ISSUE THREAD

**Issue by dcalvom** [HarryChen0506/react-markdown-editor-lite#28]
For some validation libraries in React is mandatory to have a name attribute. It would be nice to be able to add a prop `name` to the <textarea> element here: https://github.com/HarryChen0506/react-markdown-editor-lite/blob/33dee22156935e1b10dd4c7a8dbddd88fd117957/src/editor/index.jsx#L561

**Comment by HarryChen0506** [comment]
As I understand, you means that <textarea> should be added a prop `name`.What I want to make sure is that prop `name` custom (for example, `name={this.props.foo}`)? or just add a props `name='markdown-content'` ?

**Comment by HarryChen0506** [comment]
OK， I already understand what your mean. Thanks your pull request, and I have merged it.

**Comment by dcalvom** [comment]
Thanks @HarryChen0506! I just add a new pull request. The validation library I use need to access the validity state of the input, therefore is necessary to forward the event into the onEmit method. Thanks again for your help

**Comment by HarryChen0506** [comment]
yes, you are right! the best api  should contain an event detail, thank you for your contribution！

**Comment by dcalvom** [comment]
Thanks for this great package!

**Comment by dcalvom** [comment]
Would you mind to create a release with this latest change so I can install the package from npm? Sorry to bother.

**Comment by HarryChen0506** [comment]
Hello, my friend, I have published a new version(v0.4.4) in NPM. you can use it as follows. :-）
```
handleEditorChange = ({ html, text}, event) => {
    console.log('handleEditorChange', event)
  }
```

**Comment by dcalvom** [comment]
Great!!! Thanks man!

**Comment by HarryChen0506** [comment]
yes, I forgot it. I will correct it next time. Have a nice experience :-)

**Comment by dcalvom** [comment]
Thaaaanks! Sorry for bother a lot. If you can wrap that in a release, you will make my day. I'm currently patching my local version but this is not sustainable

**Comment by HarryChen0506** [comment]
I am happy to do it, so you don't have to feel sorry. I will fix it after work as soon as possible.

**Comment by dcalvom** [comment]
Awesome! You rock!

**Comment by HarryChen0506** [comment]
Hello, the latest version(v0.4.5) has been released. If you have any request, just tell us. :-)
