### ISSUE TITLE
Support for RTL

### ISSUE THREAD

**Issue by munafio** [HarryChen0506/react-markdown-editor-lite#281]
is there an API or any plans to add support to RTL? for Arabic and other related languages direction?

**Comment by sylingd** [comment]
I'm happy to support RTL, but in fact, I don't know how to support RTL, include what should I do and how can I test it. I searched on MDN, but that didn't help much.

If you have more information, such as articles, codes, you can post them below.

**Comment by munafio** [comment]
@sylingd RTL is the editor's (or DOM elements) direction (Right To Left) for languages like (Arabic, Urdu...etc) .. In English, the direction starts from Left To Right (LTR) which is by default supported.

So the components should be on the opposite direction if it was RTL, as well as the text, toolbar items ...etc

I have tested the library, and found a solution to do it .. which is by putting the Editor component inside a wrapper `div` with the following stylings:
```css
direction: rtl;
text-align:right;
```
or you can make it as a css class then set it to the wrapper `div`.

and now everything is working as expected for RTL direction.

**Comment by sylingd** [comment]
Thank you, I will support in next version

**Comment by munafio** [comment]
@sylingd No, Thanks to you for your great work .. you already did support it because of the structure ..etc, only missing the thing I've mentioned above (direction stylings) which can be a boolean property (isRTL).
