### ISSUE TITLE
Typing errors - TS2314 and TS2694

### ISSUE THREAD

**Issue by rdvojmoc** [HarryChen0506/react-markdown-editor-lite#36]
After adding react-markdown-editor-lite through npm install I get two typing errors in /lib/index.d.ts
`TS2694	(TS) Namespace 'React' has no exported member 'HTMLAttributes'.` and `TS2314	(TS) Generic type 'Promise<T>' requires 1 type argument(s).`. 

React versions:
- react: 16.9.0
- @types/react: 16.9.11

How to fix this errors?

**Comment by HarryChen0506** [comment]
@sylingd Do you have time to help solve this problem about Typescript？:-)

**Comment by rdvojmoc** [comment]
I made pull request #37 . Please review it.

**Comment by HarryChen0506** [comment]
Hello, I have published a new release(V0.4.6) to fix this problem.

**Comment by rdvojmoc** [comment]
Thanks, closing.
