### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by lin-xin** [HarryChen0506/react-markdown-editor-lite#39]
开发环境可以正常使用，build之后出现了错误，请问有遇到过吗？
![errorInfo](https://user-images.githubusercontent.com/13494930/68724200-c779dc00-05f5-11ea-96ef-d476ad03830d.png)

**Comment by HarryChen0506** [comment]
![image](https://user-images.githubusercontent.com/21263805/68725078-4a039b00-05f8-11ea-90d5-a41b65682350.png)
我猜可能是这个问题导致的，你试一下。如果不是我再看看

**Comment by lin-xin** [comment]
不行，我 import MdEditor from 'react-markdown-editor-lite'; 之后，把  <MdEditor ... > 注释掉之后，build之后还是会报错，把import也注释掉就正常了，开发环境都没问题。
我项目是 create-react-app 创建的，build 时用的是 react-app-rewired build 命令

**Comment by HarryChen0506** [comment]
我也重现了这个问题，你先把这个库降到0.4.3版本。等我修复好了，我再告诉你升级到下个版本

**Comment by lin-xin** [comment]
好的，辛苦了

**Comment by HarryChen0506** [comment]
你试试最新的版本(0.4.8), 应该解决了这个bug。原来是
```
import React, { Component } from 'react'
// React.Component这样写会报错
export class MdEditor extends React.Component {
...
}
// 改成Component就好了
export class MdEditor extends Component {
...
}
```
不知道为什么

**Comment by lin-xin** [comment]
更新到0.4.8版本，问题确实修复了，谢谢！
