### ISSUE TITLE
在Antd的From表单里无法使用

### ISSUE THREAD

**Issue by Amiaris** [HarryChen0506/react-markdown-editor-lite#42]
在Antd的From表单内无法使用，一输入就报`t.replace is not a function`的错误

**Comment by sylingd** [comment]
请参考：
https://github.com/GKD-OW/www-frontend/blob/master/pages/work/edit.tsx
https://github.com/GKD-OW/www-frontend/blob/master/components/editor/index.tsx

**Comment by Amiaris** [comment]
👌，谢谢，不过确实在getFieldDecorator里无法使用
