### ISSUE TITLE
新增一个getNavigation获取h[1-6]标题，生成标题目录

### ISSUE THREAD

**Issue by ZBKcoders** [HarryChen0506/react-markdown-editor-lite#43]
可不可以新增一个getNavigation获取h[1-6]标题，生成标题目录，点击目录滚动到指定标题下，
![image](https://user-images.githubusercontent.com/22022922/69008688-55ecb580-0988-11ea-8ae1-a0cdd7d30daf.png)类似这种，这个是我看到别人的vue，但是我比较喜欢你的简洁，但是我是个后端人员，改不来您的代码，😂，谢谢

**Comment by HarryChen0506** [comment]
理论上可以实现的，等我有空时看看怎么实现这个交互

**Comment by ZBKcoders** [comment]
好的，谢谢，https://github.com/hinesboy/mavonEditor/blob/master/src/lib/core/extra-function.js  这个是那个vue版本的，不过还是钟爱react，😂。
