### ISSUE TITLE
Disable/hide full screen option

### ISSUE THREAD

**Issue by rdvojmoc** [HarryChen0506/react-markdown-editor-lite#45]
Is there a way to disable/hide full screen option from top menu? I went through the config options but couldn't find one.
![image](https://user-images.githubusercontent.com/13537823/69262509-e400b000-0bc3-11ea-951d-d6f41b81f686.png)

**Comment by HarryChen0506** [comment]
you can hide this full screen button by css, before we update this library.
```
.rmel-icon-enlarge {
    display: none
}
```

**Comment by rdvojmoc** [comment]
Thanks, I already did that, but it would be nice to include this in configuration options.

**Comment by HarryChen0506** [comment]
Hello, I have updated library to support hide full screen in veision 0.5.0

**Comment by rdvojmoc** [comment]
Thanks.
