### ISSUE TITLE
onImageUpload执行后的回调函数能单独提供吗？

### ISSUE THREAD

**Issue by ParaSLee** [HarryChen0506/react-markdown-editor-lite#53]
`onImageUpload={(file, callback) => void}`

依照现在的做法，向callback传入url可以插入图片。

如果callback这个参数所使用的函数能单独提供出来的话，就能满足图片添加功能的二次开发，例如
做一个弹窗，能选择输入url链接或者上传图片。

同类比，工具栏上其他的功能是否也能单独提供这样的callback？
或者统一成一个方法，实现不同内容的插入？

**Comment by HarryChen0506** [comment]
这个可以实现的，有时间我处理一下

**Comment by sylingd** [comment]
> 这个可以实现的，有时间我处理一下

我觉得应该是提供一个插入内容的API

**Comment by HarryChen0506** [comment]
图片上传可以做成之前的类似onBeforeClear的api。
工具栏上其他的功能，也可以暴露出接口，回调参数有按钮类型和原始值，返回新的改变值。不过我觉得暂时没有必要做这个，搞得复杂化了。

**Comment by sylingd** [comment]
> 图片上传可以做成之前的类似onBeforeClear的api。
> 工具栏上其他的功能，也可以暴露出接口，回调参数有按钮类型和原始值，返回新的改变值。不过我觉得暂时没有必要做这个，搞得复杂化了。

我觉得下个版本可以尝试暴露更多API，把工具栏的功能做成组件化的形式

**Comment by HarryChen0506** [comment]
是的，可以将工具栏独立出来，甚至用户自行添加新功能。这样的话，要升大版本了。可以考虑保留这个开箱即用的组件，同时提供一个高度配置化的组件。

**Comment by ParaSLee** [comment]
> 这个可以实现的，有时间我处理一下

感谢

**Comment by HarryChen0506** [comment]
最近在忙另一个项目，所以这个issue解决的有些晚了，抱歉哈。刚才升到0.5.1了，你可以试一试，看看能不能实现一个自定义的图片上传对话框。如果方案不行，随时联系我们
