### ISSUE TITLE
Cannot read property 'scrollHeight' of null

### ISSUE THREAD

**Issue by vvLu** [HarryChen0506/react-markdown-editor-lite#55]
当我给外层div设置固定高度的时候 markdown内容部分滚动的时候会出现报错Cannot read property 'scrollHeight' of null

**Comment by vvLu** [comment]
我把你的代码拉下来测试了一下也出现这种问题了

![image](https://user-images.githubusercontent.com/24219565/70678045-d8d50780-1ccb-11ea-8f32-4a5e15660c45.png)
只有在双侧滚动过后才不会出现那个bug
![image](https://user-images.githubusercontent.com/24219565/70678058-e7232380-1ccb-11ea-8287-60af65603d03.png)

**Comment by HarryChen0506** [comment]
虽然代码里可以加个null判断可以解决，你能找出报错的原因吗？

**Comment by HarryChen0506** [comment]
这个问题我已修复了，稍后发布
