### ISSUE TITLE
image button

### ISSUE THREAD

**Issue by deligent-ant** [HarryChen0506/react-markdown-editor-lite#62]
图片按钮，必须是选择本地文件吗？
 参考一下 这个 支持2形式
[vue 编辑器](http://www.zhystar.com/)

**Comment by HarryChen0506** [comment]
本库提供了自定义图片上传的接口onCustomImageUpload。如果需要有定制需求，可以利用这个接口做二次开发。由于考虑大多数使用者喜好不一，故不做两种形式的上传方式。自定义的大致思路已在文档里演示了。
```
onCustomImageUpload = () => {
    return new Promise((resolve, reject) => {
      // 对话框伪代码
      YourCustomDialog.open(() => {
        setTimeout((url) => {
            // 对话框正确的回调获取到url， 无论是本地上传的，还是直接输入的
             resolve({url: url, name: 'pic'})
           }, 1000)
       })
    })
  }
```

**Comment by deligent-ant** [comment]
那个并不行啊 也没说做两种形式的上传啊，用户有时候点击 图片按钮 并不想上传图片，不过是想 生成`![]()` 这个语法而已  你连这个都不支持，都给你网址了 那个不是2种形式的上传  那用户点击图片按钮 不想上传图片怎么班  只是想生成格式好的语法

**Comment by HarryChen0506** [comment]
这个需要自己做二次开发的，接口提供给你了，你要再写个对话框来支持这两种上传方式。

**Comment by deligent-ant** [comment]
一个 下拉框就能做的交互 那才是最合理的 如果是对话框 会打断用户操作的感觉，体验很不好。就比如 你已经明确知道要不想选择图片，还要等对话框弹出来 再操作 这对用户体验是非常不友好的。既然作者不支持 ，那也没有办法了 再看看有没有更好的库了   再次对作者表示感谢
