### ISSUE TITLE
版本计划

### ISSUE THREAD

**Issue by sylingd** [HarryChen0506/react-markdown-editor-lite#72]
* [x] 重构工具栏部分，支持插拔，支持插件
* [x] 重构预览部分，并将预览按钮移动至工具栏
* [x] 改进渲染功能，支持诸如react-markdown这类将markdown渲染为ReactNode的渲染引擎
* [x] 功能：支持直接粘贴图片、图片拖拽
* [x] 功能：支持更多API，供插件使用

**Comment by HarryChen0506** [comment]
👍

**Comment by HarryChen0506** [comment]
新春快乐 @sylingd
