### ISSUE TITLE
textarea ignores 'y' and 'z'

### ISSUE THREAD

**Issue by baalansellers** [HarryChen0506/react-markdown-editor-lite#74]
With the upgrade from minor version 0.5.1. to 0.6.0, I've noticed that I can no longer type the characters 'y' and 'z' into the text area. Downgrading to 0.5.1 returns that functionality.

**Comment by HarryChen0506** [comment]
we have fixed it at v0.6.1

**Comment by baalansellers** [comment]
Thanks!
I upgraded to 0.6.1 and the trouble is gone.
