### ISSUE TITLE
Image and table plugin configuration doesn't work

### ISSUE THREAD

**Issue by jonatanklosko** [HarryChen0506/react-markdown-editor-lite#86]
The [configuration docs](https://github.com/HarryChen0506/react-markdown-editor-lite/blob/88caf25b8d8f9519ca3f3ac2447251ce08ae65ea/docs/configure.md) mentions the following editor configuration attributes: `config.imageAccept`, `config.table.maxRow`, `config.table.maxCol`, but currently none is respected (e.g. the official demo renders table plugin 6x6, even though the default configuration says 4x6).

The problem is that these plugins call `getConfig`:

https://github.com/HarryChen0506/react-markdown-editor-lite/blob/e0687f4e30df82adeb92e5ca36053cf618fe3179/src/plugins/Image/index.tsx#L82

https://github.com/HarryChen0506/react-markdown-editor-lite/blob/e0687f4e30df82adeb92e5ca36053cf618fe3179/src/plugins/table/index.tsx#L56-L57

But the `getConfig` function looks up the options in the *plugin configuration*, not the *editor configuration*:

https://github.com/HarryChen0506/react-markdown-editor-lite/blob/e0687f4e30df82adeb92e5ca36053cf618fe3179/src/plugins/Plugin.ts#L27-L31

Either the plugins should use the global configuration, or the global configuration options should be removed in favor of plugin specific configuration (in that case it would be great to have an example of how to configure the built-in plugins).

**Comment by sylingd** [comment]
fixed
