### ISSUE TITLE
Is there an example to use focus() to set focus on editor?

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [HarryChen0506/react-markdown-editor-lite#92]
When I add a ref to the component, I see there is nodeMdText.current, but it always seems to be null.

I am adding ref like this...
`ref={node => (this.mdEditor = node || undefined)}`

...and then trying...
`this.mdEditor.nodeMdText.current.focus();`

**Comment by HarryChen0506** [comment]
```
this.mdEditor.nodeMdText.current.focus()
```
There is no problem to use focus function.

**Comment by jeffbonasso-ambifi** [comment]
Yes, I am seeing something weird going on. Here is a short video that shows. For some reason I am getting null for current. Also you will see that when select text and do an action, it always puts the markdown at the beginning instead of around the text. Do you have an idea of why that may be happening?

https://youtu.be/VAoNnLNDP90

**Comment by jeffbonasso-ambifi** [comment]
I figured it out and was my problem. You can close this. The issue was the React version I was using. Was on 16.2.0. One upgraded, all worked perfect. Thanks for a great component!

**Comment by HarryChen0506** [comment]
That's wonderful!
