### ISSUE TITLE
1.0.2版本中自带插件的icon和编辑器全部样式失效

### ISSUE THREAD

**Issue by xfause** [HarryChen0506/react-markdown-editor-lite#98]
如题
React版本16.6.3
react-markdown-editor-lite版本1.0.2
![image](https://user-images.githubusercontent.com/10933534/76072182-78a3e800-5fd2-11ea-8a69-f0d5ebadcc57.png)
刷新前Menu中的插件icon丢失，刷新后Editor全局样式丢失

**Comment by sylingd** [comment]
请给出一个最小复现

**Comment by xfause** [comment]
涉及到公司业务 在搞最小复现 但是对比了之前0.5.2和1.0.2的代码 发现有可能是lib下的css文件被压缩导致的…页面元素下没有对应的样式

**Comment by sylingd** [comment]
> 涉及到公司业务 在搞最小复现 但是对比了之前0.5.2和1.0.2的代码 发现有可能是lib下的css文件被压缩导致的…页面元素下没有对应的样式

新版本需要自行导入lib下面的css

**Comment by xfause** [comment]
> > 涉及到公司业务 在搞最小复现 但是对比了之前0.5.2和1.0.2的代码 发现有可能是lib下的css文件被压缩导致的…页面元素下没有对应的样式
> 
> 新版本需要自行导入lib下面的css

多谢问题已解决。
另有问题

```
index.js
<MdEditor
   .....
   onChange={()=>{
     this.interval=setInterval(()=>{
       this.setState({value: value},()=>{
         MdEditor.use(MyPlugin,{
            props:this.state.value
         })
         clearInterval(this.interval)
      })
      },1000)
   }}
>

Myplugin.js
class MyPlugin extends PluginComponent {
   .....
   render(){
     return <span>this.props.config.value</span>
   }
}
```

此时MyPlugin中的this.props.config.value不会即时更新 请问如何处理

**Comment by sylingd** [comment]
不要这样使用。
如果是组件内部进行自增或者类似操作，用setState操作自己的state。
如果是来源于外部的，或者是几个组件共享的，考虑通过redux这类东西共享状态，或者通过events这类库进行事件监听然后forceUpdate/setState。
