### ISSUE TITLE
Underline is not working.

### ISSUE THREAD

**Issue by singhiam** [HarryChen0506/react-markdown-editor-lite#99]
Hi, 

Rest of the plugins are all working for me but Underline is not working.

**Comment by HarryChen0506** [comment]
if you are using 'markdown-it' as the parser, you need to import  'markdown-it-ins' plugin for <ins> ins </ins> html tag.

```
import * as MarkdownIt from 'markdown-it';
import insert from 'markdown-it-ins'

this.mdParser = new MarkdownIt({
      html: true,
      linkify: true,
      typographer: true,
      highlight(str, lang) {},
    }).use(insert)
```

**Comment by singhiam** [comment]
Thanks @HarryChen0506  Its working now.
